# It is convenient to use AWS CLI and eksctl(version 0.194.0 or later) to create this ServiceAccount request.
# See https://docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.html

############################
# 1. Create an IAM policy  #
############################

# Save the following JSON file to your local computer directory.
#
# {
#     "Version": "2012-10-17",
#     "Statement": [
#         {
#             "Effect": "Allow",
#             "Action": [
#                 "license-manager:CheckoutLicense",
#                 "license-manager:ExtendLicenseConsumption",
#                 "license-manager:ListReceivedLicenses",
#                 "license-manager:CheckInLicense",
#                 "license-manager:GetLicense"
#             ],
#             "Resource": "*"
#         }
#     ]
# }
#
# And using the AWS CLI:
#
#   aws iam create-policy --policy-name [POLICY_NAME] --policy-document file://[PATH_TO_POLICY.json]
#


#############################
# 2. Create ServiceAccount  #
#############################

# Using the eksctl tool:
#
#   eksctl create iamserviceaccount --namespace [NAMESPACE] --name [SERVICE_ACCOUNT_NAME] \
#     --cluster [EKS_CLUSTER_NAME] --role-name [ROLE_NAME] \
#     --attach-policy-arn arn:aws:iam::[AWS_ACCOUNT_ID]:policy/[POLICY_NAME] --approve
#
# where
#
#   - [NAMESPACE] is the namespace you want to launch the Friendli Container pods.
#     (e.g. default)
#   - [SERVICE_ACCOUNT_NAME] is the name of the newly created Kubernetes ServiceAccount.
#     (e.g. friendli-container-service-account)
#   - [EKS_CLUSTER_NAME] is the name of the EKS cluster.
#   - [ROLE_NAME] is the name of the IAM role to be created.
#   - [AWS_ACCOUNT_ID] is the numeric ID of your AWS account.
#   - [POLICY_NAME] is the name of the policy created during the previous step.


apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: friendli-container-service-account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::[AWS_ACCOUNT_ID]:policy/[POLICY_NAME]
  labels:
    app.kubernetes.io/managed-by: eksctl
