# You can use kubectl tool to create this resource.
#
# kubectl create secret generic [SECRET_NAME] -n [NAMESPACE] \
#   --from-literal container_secret=AWS_EKS_LICENSE_MANAGER \
#   --from-literal huggingface_token=[HUGGINGFACE_TOKEN]
#
# where
#   - [SECRET_NAME] is the name of the secret (e.g. friendli-container-secret)
#   - [NAMESPACE] is the namespace you want to launch the Friendli Container pods.
#     (e.g. default)
#   - [HUGGINGFACE_TOKEN] is the HuggingFace API token. (optional)


apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: friendli-container-secret
type: Opaque
data:
  container_secret: QVdTX0VLU19MSUNFTlNFX01BTkFHRVI=
  huggingface_token: [REDACTED]
