# FriendliConfig contains the required configurations to launch your FriendliDeployments.
# FriendliConfig is required in the each namespace in which you want to create FriendliDeployments.


apiVersion: friendli.ai/v1alpha1
kind: FriendliConfig
metadata:
  namespace: default
  name: friendli-container-config
spec:
  serviceAccountName: friendli-container-service-account
  containerSecret:
    name: friendli-container-secret
    key: container_secret
  modelRepositorySecrets:
    huggingFaceToken:
      name: friendli-container-secret
      key: huggingface_token
