apiVersion: friendli.ai/v1alpha1
kind: FriendliDeployment
metadata:
  namespace: default
  name: friendlideployment-sample
spec:
  engine:
    image: 709825985650.dkr.ecr.us-east-1.amazonaws.com/friendliai/friendli-container:v1.7.16-eks
  model:
    huggingFace:
      #
      # For gated or private models, pproval for your HuggingFace account
      # is needed and you should provide HuggingFace API key.
      # See ./secret.yaml and ./friendli-config.yaml for the details.
      #
      repository: Qwen/Qwen2.5-1.5B-Instruct
  resources:
    #
    # Replace with appropriate NodeSelector for your environment.
    #
    nodeSelector:
      node.kubernetes.io/instance-type: g5.4xlarge

    #
    # When designating resource limits and requests:
    #
    #   - You should consider whether your EKS nodes have ephemeral storage or not.
    #   - Memory size should be larger than the size of your LLM model of choice.
    #
    requests:
      cpu: "4"
      nvidia.com/gpu: "1"
    limits:
      cpu: "4"
      nvidia.com/gpu: "1"
